package db

var titles = []string{
	"Getting Started with Go",
	"10 Tips for Better Code",
	"Understanding Concurrency",
	"Building REST APIs",
	"Database Design Patterns",
	"Microservices Architecture",
	"Clean Code Principles",
	"Testing Best Practices",
	"Docker for Beginners",
	"Kubernetes Essentials",
	"GraphQL vs REST",
	"Authentication Strategies",
	"Caching Techniques",
	"Performance Optimization",
	"Error Handling Patterns",
	"Logging and Monitoring",
	"CI/CD Pipeline Setup",
	"Security Best Practices",
	"API Versioning Guide",
	"Working with WebSockets",
	"Message Queue Basics",
	"Event-Driven Design",
	"Domain-Driven Design",
	"Refactoring Legacy Code",
	"Code Review Guidelines",
	"Git Workflow Strategies",
	"Debugging Techniques",
	"Memory Management",
	"Dependency Injection",
	"Design Patterns Overview",
	"Functional Programming",
	"Object-Oriented Principles",
	"Data Structures Guide",
	"Algorithm Optimization",
	"API Documentation Tips",
	"Rate Limiting Strategies",
	"Load Balancing Basics",
	"Database Indexing",
	"SQL Query Optimization",
	"NoSQL Database Choices",
	"Serverless Architecture",
	"Cloud Deployment Guide",
	"Infrastructure as Code",
	"Monitoring Best Practices",
	"Scaling Applications",
	"High Availability Setup",
	"Disaster Recovery Plans",
	"Data Migration Strategies",
	"API Gateway Patterns",
	"Service Mesh Overview",
}

var contents = []string{
	"In this post, we explore the fundamentals and best practices for modern software development.",
	"Learn how to improve your coding skills with these practical tips and techniques.",
	"Understanding the core concepts is essential for building robust applications.",
	"This guide walks you through the step-by-step process of implementation.",
	"Discover the key principles that separate good code from great code.",
	"We dive deep into the architecture patterns that scale effectively.",
	"Exploring common pitfalls and how to avoid them in your projects.",
	"A comprehensive overview of the tools and techniques you need to know.",
	"Breaking down complex concepts into easy-to-understand explanations.",
	"Real-world examples that demonstrate practical applications.",
	"Tips and tricks learned from years of production experience.",
	"How to approach problems systematically for better solutions.",
	"The essential guide for developers at any skill level.",
	"Comparing different approaches and when to use each one.",
	"Lessons learned from building and maintaining large systems.",
	"A practical introduction to concepts that matter most.",
	"Strategies for writing maintainable and testable code.",
	"How to think about trade-offs when making technical decisions.",
	"The fundamentals every developer should master.",
	"Advanced techniques for experienced practitioners.",
	"Common mistakes and how to fix them quickly.",
	"Building for reliability and performance from day one.",
	"What I wish I knew when I started my development journey.",
	"The complete guide to getting things done right.",
	"Practical advice for everyday development challenges.",
	"How to level up your skills with deliberate practice.",
	"Understanding the why behind the how.",
	"From beginner to expert: a structured learning path.",
	"The art and science of writing quality software.",
	"Making complex systems simple and understandable.",
	"Key insights from working on production systems.",
	"How to build systems that stand the test of time.",
	"The developer's guide to continuous improvement.",
	"Patterns and practices for modern development.",
	"Solving real problems with elegant solutions.",
	"The mindset shift that improved my code quality.",
	"How to approach new technologies effectively.",
	"Building a strong foundation for future growth.",
	"The principles that guide successful projects.",
	"Practical wisdom for the working developer.",
	"How to balance speed and quality in development.",
	"The hidden complexity behind simple features.",
	"Strategies for managing technical debt.",
	"How to communicate technical ideas effectively.",
	"Building systems that are easy to change.",
	"The importance of simplicity in software design.",
	"How to learn from failures and mistakes.",
	"Creating value through thoughtful engineering.",
	"The path to becoming a better developer.",
	"Embracing change as a constant in software.",
}

var comments = []string{
	"Great post! This really helped me understand the concept.",
	"Thanks for sharing this. Very informative!",
	"I've been struggling with this for weeks. Finally makes sense!",
	"Could you elaborate more on the second point?",
	"This is exactly what I was looking for.",
	"Excellent explanation. Bookmarking this for later.",
	"I disagree with some points, but overall good content.",
	"Have you considered an alternative approach?",
	"This saved me hours of debugging. Thank you!",
	"Well written and easy to follow.",
	"I tried this and it works perfectly.",
	"Can you provide more examples?",
	"This is a bit outdated. Things have changed since then.",
	"Brilliant! Sharing this with my team.",
	"I had a similar experience. Great insights.",
	"What about edge cases? How would you handle those?",
	"Super helpful. Keep up the great work!",
	"I would add that you should also consider performance.",
	"Nice article. Looking forward to more content like this.",
	"This clarified a lot of my doubts.",
	"How does this compare to other solutions?",
	"I implemented this in my project. Works great!",
	"Clear and concise. Exactly what documentation should be.",
	"Any plans to cover advanced topics?",
	"This is the best explanation I've found online.",
	"Learned something new today. Thanks!",
	"Would love to see a follow-up post on this.",
	"I've been doing it wrong all this time!",
	"Solid advice. Will definitely apply this.",
	"Can you recommend any additional resources?",
	"This approach is much cleaner than what I was doing.",
	"Thanks for the detailed walkthrough.",
	"I have a question about the implementation.",
	"This is going straight to my notes.",
	"Incredibly useful. Appreciate the effort.",
	"How would this scale in production?",
	"Simple yet effective. Love it.",
	"I wish I had found this earlier.",
	"Great job breaking down complex topics.",
	"This deserves more attention.",
	"Exactly the solution I needed.",
	"Very practical advice. Thanks for sharing.",
	"I respectfully disagree. Here's why...",
	"Mind blown! Never thought of it this way.",
	"Adding this to my toolkit.",
	"Clean code and great explanation.",
	"This is gold. Thank you!",
	"Looking forward to trying this out.",
	"Fantastic resource for beginners.",
	"You made this look so easy!",
}

var tags = []string{
	"golang",
	"programming",
	"backend",
	"api",
	"database",
	"docker",
	"kubernetes",
	"microservices",
	"testing",
	"devops",
	"security",
	"performance",
	"architecture",
	"design-patterns",
	"best-practices",
	"tutorial",
	"beginners",
	"advanced",
	"tips",
	"guide",
	"web",
	"cloud",
	"aws",
	"linux",
	"git",
	"sql",
	"nosql",
	"redis",
	"postgres",
	"mongodb",
	"graphql",
	"rest",
	"grpc",
	"websocket",
	"authentication",
	"authorization",
	"caching",
	"logging",
	"monitoring",
	"debugging",
	"refactoring",
	"clean-code",
	"solid",
	"tdd",
	"ci-cd",
	"automation",
	"scalability",
	"reliability",
	"serverless",
	"opensource",
}

var usernames = []string{
	"Alex",
	"Jordan",
	"Taylor",
	"Morgan",
	"Casey",
	"Riley",
	"Quinn",
	"Avery",
	"Parker",
	"Skyler",
	"Charlie",
	"Dakota",
	"Reese",
	"Finley",
	"Sawyer",
	"Emerson",
	"Rowan",
	"Blake",
	"Cameron",
	"Drew",
	"Jamie",
	"Kendall",
	"Logan",
	"Peyton",
	"River",
	"Sage",
	"Spencer",
	"Hayden",
	"Micah",
	"Phoenix",
	"Adrian",
	"Ash",
	"Bailey",
	"Blair",
	"Corey",
	"Devin",
	"Ellis",
	"Frankie",
	"Gray",
	"Harper",
	"Indigo",
	"Jesse",
	"Kerry",
	"Lane",
	"Marley",
	"Nico",
	"Oakley",
	"Pat",
	"Raven",
	"Sam",
}
